import { DateRange } from './date-range.model';

export const dateRangeCollectionMock: DateRange[] = [
  { code: 'L60BDL',
    displayCode: 'L60 Days',
    v2ApiCode: 'L60',
    description: 'Last 60 Days Of Current Year With Business Day Lag',
    range: '04/04/17 - 06/02/17' },
  { code: 'L90BDL',
    displayCode: 'L90 Days',
    v2ApiCode: 'L90',
    description: 'Last 90 Days Of Current Year With Business Day Lag',
    range: '03/05/17 - 06/02/17' },
  { code: 'CYTM',
    displayCode: 'CYTM',
    v2ApiCode: 'CYTM',
    description: 'From First Day of Current Calendar Year to Last Closed Month',
    range: '01/01/17 - 05/31/17' },
  { code: 'FYTM',
    displayCode: 'FYTM',
    v2ApiCode: 'FYTM',
    description: 'From First Day of Current Fiscal Year to Last Closed Month',
    range: '03/01/17 - 05/31/17' },
  { code: 'FYTDBDL',
    displayCode: 'FYTD',
    v2ApiCode: 'FYTD',
    description: 'Current Fiscal Year to Date With Business Day Lag',
    range: '03/01/17 - 06/02/17' },
  { code: 'L3CM',
    displayCode: 'L03 Mth',
    v2ApiCode: 'L03',
    description: 'Last 3 Closed Months',
    range: '03/01/17 - 05/31/17' },
  { code: 'LCM',
    displayCode: 'Clo Mth',
    v2ApiCode: 'CMTH',
    description: 'Last Closed Month Of Current Year',
    range: '05/01/17 - 05/31/17' },
  { code: 'MTD',
    displayCode: 'MTD',
    v2ApiCode: 'MTD',
    description: 'Current Month to Date',
    range: '06/01/17 - 06/09/17' },
  { code: 'L120BDL',
    v2ApiCode: 'L120',
    displayCode: 'L120 Days',
    description: 'Last 120 Days Of Current Year With Business Day Lag',
    range: '02/03/17 - 06/02/17' },
  { code: 'CYTDBDL',
    displayCode: 'CYTD',
    v2ApiCode: 'CYTD',
    description: 'From First Day of Current Calendar Year to Date With Business Day Lag',
    range: '01/01/17 - 06/02/17' }
];
