export enum EntityPeopleType {
  'KEY ACCOUNT MANAGER' = <any>'KEY ACCOUNT MANAGER',
  'NATIONAL ACCOUNT MANAGER' = <any>'NATIONAL ACCOUNT MANAGER',
  'CHAIN DIRECTOR' = <any>'CHAIN DIRECTOR',
  'CHANNEL LEAD' = <any>'CHANNEL LEAD',
  'CORPORATE' = <any>'CORPORATE',
  'GENERAL MANAGER' = <any>'GENERAL MANAGER',
  'MARKET DEVELOPMENT MANAGER' = <any>'MARKET DEVELOPMENT MANAGER',
  'ON PREM ACTIVATION MANAGER' = <any>'ON PREM ACTIVATION MANAGER',
  'ON PREM ACTIVATION SPECIALIST' = <any>'ON PREM ACTIVATION SPECIALIST',
  'ON PREM DIRECTOR' = <any>'ON PREM DIRECTOR',
  'ON PREM MANAGER' = <any>'ON PREM MANAGER',
  'ON PREM VICE PRESIDENT' = <any>'ON PREM VICE PRESIDENT',
  'SALES LEADERSHIP' = <any>'SALES LEADERSHIP',
  'TEAM LEAD' = <any>'TEAM LEAD'
}

export enum EntityPropertyType {
  Distributor = <any>'Distributor',
  Account = <any>'Account',
  SubAccount = <any>'SubAccount'
}
