export enum EntityPeopleType {
  'KEY ACCOUNT MANAGER' = 'KEY ACCOUNT MANAGER',
  'NATIONAL ACCOUNT MANAGER' = 'NATIONAL ACCOUNT MANAGER',
  'CHAIN DIRECTOR' = 'CHAIN DIRECTOR',
  'CHANNEL LEAD' = 'CHANNEL LEAD',
  'CORPORATE' = 'CORPORATE',
  'GENERAL MANAGER' = 'GENERAL MANAGER',
  'MARKET DEVELOPMENT MANAGER' = 'MARKET DEVELOPMENT MANAGER',
  'ON PREM ACTIVATION MANAGER' = 'ON PREM ACTIVATION MANAGER',
  'ON PREM ACTIVATION SPECIALIST' = 'ON PREM ACTIVATION SPECIALIST',
  'ON PREM DIRECTOR' = 'ON PREM DIRECTOR',
  'ON PREM MANAGER' = 'ON PREM MANAGER',
  'ON PREM VICE PRESIDENT' = 'ON PREM VICE PRESIDENT',
  'SALES LEADERSHIP' = 'SALES LEADERSHIP',
  'TEAM LEAD' = 'TEAM LEAD',
  'OFF PREMISE SPECIALIST' = 'OFF PREMISE SPECIALIST'
}

export enum EntityPropertyType {
  Distributor = 'Distributor',
  Account = 'Account',
  SubAccount = 'SubAccount'
}
