export enum ListsActionTypes {
  FETCH_STORE_DETAILS = '[StoreDetails] FETCH_STORE_DETAILS',
  FETCH_STORE_DETAILS_SUCCESS = '[StoreDetails] FETCH_STORE_DETAILS_SUCCESS',
  FETCH_STORE_DETAILS_FAILURE = '[StoreDetails] FETCH_STORE_DETAILS_FAILURE',
  FETCH_HEADER_DETAILS = '[StoreDetails] FETCH_HEADER_DETAILS',
  FETCH_HEADER_DETAILS_SUCCESS = '[StoreDetails] FETCH_HEADER_DETAILS_SUCCESS',
  FETCH_HEADER_DETAILS_FAILURE = '[StoreDetails] FETCH_HEADER_DETAILS_FAILURE'
}
