export enum NotificationObjectType {
  'TARGET_LIST' = 'TARGET_LIST',
  'OPPORTUNITY' = 'OPPORTUNITY',
  'STORE' = 'STORE',
  'ACCOUNT' = 'ACCOUNT',
  'DISTRIBUTOR' = 'DISTRIBUTOR',
  'LIST' = 'LIST'
}

export enum NotificationAction {
  'SHARE_TARGET_LIST' = 'SHARE_TARGET_LIST',
  'SHARE_OPPORTUNITY' = 'SHARE_OPPORTUNITY',
  'ADDED_NOTE' = 'ADDED_NOTE',
  'ARCHIVE_TARGET_LIST' = 'ARCHIVE_TARGET_LIST',
  'LIST_COLLABORATOR_ADDED' = 'LIST_COLLABORATOR_ADDED',
  'LIST_OWNER_CHANGED' = 'LIST_OWNER_CHANGED'
}

export enum NotificationStatus {
  'SEEN' = 'SEEN',
  'READ' = 'READ',
  'UNSEEN' = 'UNSEEN'
}
